services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_php_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["php-fpm"]

  web:
    image: nginx:latest
    container_name: api_php_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
