services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_php_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["php-fpm"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://symfony:secret@db:5432/symfony?serverVersion=17&charset=utf8

  web:
    image: nginx:latest
    container_name: api_php_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: symfony_postgres
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: